dist: xenial
language: rust
rust:
  - nightly
  - beta
  - stable
env:
  - GTK=3.14 FEATURES=
  - GTK=3.24 FEATURES=v3_16
  - GTK=3.96 FEATURES=
addons:
  apt:
    packages:
    - libgtk-3-dev
    - libmount-dev
script:
  - rustc --version
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - if [ "$GTK" == "3.96" ]; then
    git clone -q --depth 50 https://github.com/sfanxiang/gtk-rs-examples4 _examples;
    else
    git clone -q --depth 50 -b pending https://github.com/gtk-rs/examples _examples;
    fi
  - cd _examples
  - ./build_travis.sh
